.PHONY: clean All

All:
	@echo "----------Building project:[ Section03 - Debug ]----------"
	@cd "Workspace" && "$(MAKE)" -f  "Section03.mk"
clean:
	@echo "----------Cleaning project:[ Section03 - Debug ]----------"
	@cd "Workspace" && "$(MAKE)" -f  "Section03.mk" clean
